import Head from "next/head";

function Heads() {
    return (
        <Head>
            <title>News Api App</title>
            <meta name="description" content="Generated by create next app" />
        </Head>
    )
}
export default Heads;
