export const GET_ALL_NEWS_SUCCESS = "GET_ALL_NEWS_SUCCESS";
export const GET_ALL_NEWS_LOADING = "GET_ALL_NEWS_LOADING";
export const GET_ALL_NEWS_ERROR = "GET_ALL_NEWS_ERROR";


export const GET_TOP_HEADLINES_SUCCESS = "GET_TOP_HEADLINES_SUCCESS";
export const GET_TOP_HEADLINES_LOADING = "GET_TOP_HEADLINES_LOADING";
export const GET_TOP_HEADLINES_ERROR = "GET_TOP_HEADLINES_ERROR";